---

- name: first make sure dest exists.
  file: dest={{ ovc_install_dir }}/Platform-Dynamic-Objects/config state=directory

- name: Copy out the unifiedConfig files
  copy: src={{ item }} dest={{ ovc_install_dir }}/Platform-Dynamic-Objects/config/ owner=jetty
  with_fileglob:
    - env_files/*.properties.*
  become: yes
  become_user: root

- name: Copy out the unifiedConfig files
  copy: src={{ item }} dest=/var/www/html/ovcdashboard/app/Config/ owner=www-data
  with_fileglob:
    - env_files/*.php.*
  become: yes
  become_user: root
