---

- name: first make sure dest exists. 
  file: dest={{ ovc_install_dir }}/Platform-Dynamic-Objects/config state=directory

- name: Copy out the unifiedConfig files
  copy: src={{ item }} dest={{ ovc_install_dir }}/Platform-Dynamic-Objects/config/ owner=jetty
  with_fileglob:
    - /opt/ansible/playbooks/roles/oneview/files/*.properties.*
  sudo: yes
