---
# These tasks install http and the php modules.

# Defining and adding  Remi Repo

- name: Add remi repo file
  template: src=remi.repo.j2 dest=/etc/yum.repos.d/remi.repo owner=root group=root mode=0644
  become: yes
  become_user: root
  when: ansible_distribution == 'CentOS'

- name: Add remi repo key
  get_url: url=http://rpms.famillecollet.com/RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi sha256sum=b0d1d4ca043e2bd60ff71899b5c0145af64f9c0ec6f2073357dfb64deada59e4 force=yes
  become: yes
  become_user: root
  when: ansible_distribution == 'CentOS'

- name: Set permissions on remi repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi owner=root group=root mode=0644
  when: ansible_distribution == 'CentOS'

- name: Add remi gpg repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi
  become: yes
  become_user: root
  when: ansible_distribution == 'CentOS'

- name: install the 'Development Tools' package group
  yum:
    name: "@Development Tools"
    state: present
  become: yes
  become_user: root
  when: ansible_distribution == 'CentOS'

- name: Set packages for CentOS
  when: ansible_distribution == 'CentOS'
  set_fact:
    php_packages:
      - php-common
      - php-devel
      - php
      - freetds
      - php-mysqlnd
      - php-pdo
      - php-odbc
      - php-xml
      - php-mbstring

- name: Set packages for Amazon
  when: ansible_distribution == 'Amazon'
  set_fact:
    php_packages:
      - httpd24
      - php55
      - freetds
      - php55-common
      - php55-devel
      - php55-mysqlnd
      - php55-pdo
      - php55-odbc
      - php55-xml
      - php55-mbstring
      - php55-pdo

- name: Install PHP packages
  yum: name={{ item }}
    state=present
  with_items: "{{ php_packages }}"
  become: yes
  become_user: root

- name: Create www-data group
  group:
    name="{{ webserver_user }}"
    state=present
    system=yes
  become: yes
  become_user: root

- name: Create www-data user
  user:
    name="{{ webserver_user }}"
    group="{{ webserver_user }}"
    state=present
    system=yes
  become: yes
  become_user: root

- name: Setup Apache httpd.conf
  template:
    src=httpd.conf.j2
    dest=/etc/httpd/conf/httpd.conf
    owner=root
    group=root
    mode=0644
  become: yes
  become_user: root

- name: Enable freetds when using MS-SQL
  template:
    src=freetds.conf.j2
    dest=/etc/freetds.conf
    owner=root
    group=root
    mode=0644
  when: "{{ ovcDB_scheme | search('.*sqlserver.*') }}"
  become: yes
  become_user: root

- name: httpd service started
  service: name=httpd state=started enabled=yes
  become: yes
  become_user: root
