---
# These tasks install http and the php modules.

# Defining and adding  Remi Repo

- name: Add repo file
  template: src=remi.repo.j2 dest=/etc/yum.repos.d/remi.repo owner=root group=root mode=0644

- name: Add repo url
  get_url: url=http://rpms.famillecollet.com/RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi sha256sum=b0d1d4ca043e2bd60ff71899b5c0145af64f9c0ec6f2073357dfb64deada59e4 force=yes
  sudo: yes

- name: Add remi repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi owner=root group=root mode=0644

- name: Add remi gpg repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi
  sudo: yes
- name: include EPEL Repo
  yum:
    name=http://mirror.cogentco.com/pub/linux/epel/epel-release-latest-7.noarch.rpm
    state=present
  sudo: yes

- name: import EPEL repo key
  rpm_key:
    key=http://mirror.cogentco.com/pub/linux/epel/RPM-GPG-KEY-EPEL-7
    state=present
  sudo: yes

- name: install the 'Development Tools' package group
  yum:
    name: "@Development Tools"
    state: present
  sudo: yes

#- name: Running Yum Updates
#  yum: name=*
#    state=latest
#  sudo: yes

- name: Install PHP packages
  yum: name={{ item }}
    state=present
  with_items:
#     - httpd-2.4.6-31.el7.centos.x86_64
     - php55w-common
     - php55w-devel
     - php55
     - freetds
     - php55w-mysqlnd
     - php55w-pdo
     - php55w-odbc
     - php55w-xml
     - php55w-mbstring
  sudo: yes

- name: Create "{{ webserver_user }}" group
  group:
    name="{{ webserver_user }}"
    state=present
    system=yes
  sudo: yes

- name: Create "{{ webserver_user }}" user
  user:
    name="{{ webserver_user }}"
    group="{{ webserver_user }}"
    state=present
    system=yes
  sudo: yes

- name: Setup Apache httpd.conf
  template:
    src=httpd.conf.j2
    dest=/etc/httpd/conf/httpd.conf
    owner=root
    group=root
    mode=0644
  sudo: yes

- name: Enable freetds when using MS-SQL
  template:
    src=freetds.conf.j2
    dest=/etc/freetds.conf
    owner=root
    group=root
    mode=0644
  when: "{{ ovcDB_scheme | search('.*sqlserver.*') }}"
  sudo: yes

- name: httpd service started
  service: name=httpd state=started enabled=yes
  sudo: yes
