---
- include: oneview.yml
  tags: server

- include: dashboard.yml
  tags: dashboard

- include: importers.yml
  tags:
    - importers
    - coreimporters
  notify:
    - Restart Jetty
    - Restart Apache
