---
- include: oneview.yml
  tags: server

- include: dashboard.yml
  tags: dashboard

- name: Start Jetty
  service:
    name: jetty
    state: started
    enabled: yes
  tags: importers
  sudo: yes

- include: importers.yml
  tags: importers
  notify:
    - Restart Jetty
    - Restart Apache
