- name: Finding latest Amazon Linux ami
  ec2_ami_find:
    name: "amzn-ami-hvm-*.0.x86_64-gp2"
    sort: name
    sort_order: descending
    region: "{{ ami_region }}"
    sort_end: 1
  register: al_ami_find
  when: customer == 'vanilla'

- set_fact:
    _ami_customer: "{{ force_ami_customer }}"
  when: force_ami_customer is defined

- set_fact:
    _ami_customer: "{{ ami_customer }}"
  when: force_ami_customer is undefined

- name: Finding latest OVC customised Amazon Linux ami
  ec2_ami_find:
    name: "ovc-{{ ovc_version }}*"
    sort: name
    sort_order: descending
    region: "{{ ami_region }}"
    sort_end: 1
    owner: "{{ ami_owner }}"
    no_result_action: fail
    ami_tags:
      customer: "{{ _ami_customer }}"
      release: "{{ ami_release }}"
  register: ovc_ami_find
  when: customer != 'vanilla'

- set_fact:
    ami_find: "{{ al_ami_find }}"
  when: customer == 'vanilla'

- set_fact:
    ami_find: "{{ ovc_ami_find }}"
  when: customer != 'vanilla'


- name: AMI ID found
  debug: "var=ami_find.results"
