- name: Finding latest Amazon Linux ami
  ec2_ami_find:
    name: "ovc-{{ ovc_version }}*"
    sort: name
    sort_order: descending
    region: "{{ region }}"
    sort_end: 1
    owner: "{{ ami_owner }}"
    ami_tags:
      customer: "{{ ami_customer }}"
      release: "{{ ami_release }}"
  register: ami_find

- name: AMI ID found
  debug: "var=ami_find.results"
