environments:
  dev:
    name: dev
    url: dev.ovcdtc.com
    mysql_host: mysql-dev.ovcdtc.com
    nosql_host: mongodb-dev.ovcdtc.com
    nosql_port: 27000
    mongo_uri: mongodb://root:root@mongodb01-dev.ovcdtc.com:27000,mongodb02-dev.ovcdtc.com:27000,mongodb03-dev.ovcdtc.com:27000/dev_promo?authSource=dev_promo
    sqs_or_sns_config: https://sqs.eu-west-1.amazonaws.com/063725663692/dtrc
    staff_discount_bucket:
    ecommerce_host: internal-epic-qa1-hyb-elb-313320281.us-west-2.elb.amazonaws.com
    crosschannel_host: cc-dev.ovcdtc.com
    port_host: devim.ovcdtc.com
