---

- name: first make sure dest exists.
  file:
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config"
    state: directory

- name: template out the unifiedConfig.properties files
  template:
    src: unifiedConfig.properties.j2
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties.{{ item.value.name }}"
    owner: jetty
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"
  when: item.value.name != 'tpqa.ovcdemo.com' and item.value.name != 'tpdev.ovcdemo.com'

- name: template out the unifiedConfig.properties files
  template:
    src: unifiedConfig.properties.tp.j2
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties.{{ item.value.name }}"
    owner: jetty
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"
  when: item.value.name == 'tpqa.ovcdemo.com' or item.value.name == 'tpdev.ovcdemo.com'

- name: template out the tools.properties files
  template:
    src: tools.properties.j2
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties.{{ item.value.name }}"
    owner: jetty
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the context.xml files
  template:
    src: context.xml.j2
    dest: "/opt/jetty/webapps/context.xml.{{ item.value.name }}"
    owner: jetty
    group: jetty
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the database/settings_var.php files
  template:
    src: database.php.j2
    dest: "/var/www/html/ovcdashboard/app/Config/.{{ item.value.name }}"
    owner: www-data
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the database/settings_var.php files
  template:
    src: setting_var.php.j2
    dest: "/var/www/html/ovcdashboard/app/Config/.{{ item.value.name }}"
    owner: www-data
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: Copy the war.xml patch files
  copy:
    src: "{{ item }}"
    dest: /opt/ovc/posWebapp/WEB-INF/
    owner: jetty
    group: jetty
  with_fileglob:
    - cometd/web.xml.patch.*
  become: yes
  become_user: root

- name: template out the database/settings_var.php files
  lineinfile:
    line: "<Set name=\"extraClasspath\">/opt/ovc/lib/ext/TPExtensions-{{ tp_extension_version|default(5.13.1) }}.jar;/opt/ovc/lib/ext/TPPopulators-{{ tp_extension_version|default(5.13.1) }}.jar</Set>"
    insertafter: <Set name="overrideDescriptor">/opt/jetty/webapps/pos.d/pos-override.xml</Set>
  become: yes
  become_user: root
  with_dict: "{{ environments }}"
  when: item.value.name == 'tpdev.ovcdemo.com' or tem.value.name == 'tpqa.ovcdemo.com'
