---
- name: See if monit is already installed
  stat:
    path: /usr/bin/monit
  register: monit_stat

- name: See if monit is the correct version
  stat:
    path: "{{ monit_home }}/monit-{{ monit_version }}"
  register: monit_stat_version

- name: See if monit service is already configured
  stat:
    path: /etc/init.d/monit
  register: monit_stat_service

- name: Stop monit
  service:
    name: monit
    state: stopped
  when: monit_stat_service.stat.exists

- name: Create directory
  file:
    path: "{{ monit_home }}"
    state: directory
    owner: root
    group: root
  become: yes
  become_user: root

- name: Unzip monit
  unarchive:
    copy: yes
    src: "monit-{{ monit_version }}-linux-x64.tar.gz"
    dest: "{{ monit_home }}/"
    owner: root
    group: root
  become: yes
  become_user: root
  when: not monit_stat_version.stat.exists

# - name: Copy monit to /usr/bin
#   command: "cp {{ monit_home }}/monit-{{ monit_version }}/bin/monit /usr/bin/monit"
#   become: yes
#   become_user: root
  # when: not monit_stat_version.stat.exists

- name: Create symlink
  file:
    src: "{{ monit_home }}/monit-{{ monit_version }}/bin/monit"
    dest: "/usr/bin/monit"
    owner: root
    group: root
    state: link
  become: yes
  become_user: root

- name: Create init.d
  template:
    src: monit.j2
    dest: /etc/init.d/monit
    mode: 0755
    owner: root
    group: root
  become: yes
  become_user: root
  when: not monit_stat_version.stat.exists
