---

- name: Create RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds

- name: Build Mongo Cluster
  hosts: localhost
  connection: local
  tasks:
    - pause:
        prompt: Please confirm that mongodb-{{ deploy_type }}.ovchosting.co.uk is available, press enter when ready.
  tags:
    - mongo

- name: Find AMI ID
  hosts: localhost
  connection: local
  roles:
    - findovcami
  tags:
    - find_ovc_ami
    - launch_ami

- name: Add AMI ID to facts
  hosts: localhost
  connection: local
  tasks:
    - name: Use set_fact to AMI
      set_fact:
        image_id: "{{ ami_find.results[0].ami_id }}"
      when: image_id is undefined
  tags:
    - find_ovc_ami
    - launch_ami


- name: Launch instance for UAT1
  hosts: localhost
  connection: local
  tasks:
    - name: Display new AMI ID
      debug:
        msg="UAT1 will now be launched with {{ image_id }}"
    - name: Present new AMI ID
      pause:
        prompt: UAT1 will now be launched with {{ image_id }}
        seconds: 30
    - name: Launch instance
      ec2:
        assign_public_ip: yes
        region: "{{ region }}"
        key_name: "{{ key }}"
        group_id: "{{ group_id }}"
        instance_type: "{{ instance_type_single }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        image: "{{ image_id }}"
        instance_profile_name: NonProdAppServer
        user_data: "{{ lookup('file', 'scripts/user_data.sh') }}"
        termination_protection: yes
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: {{ deploy_type }}.ovchosting.co.uk
          role: webapp
          environment: {{ deploy_type }}
        instance_tags:
          Name: {{ deploy_type }}.ovchosting.co.uk
          role: webapp
          environment: {{ deploy_type }}
      register: ami_instance
    - name: Add new Route53 entry
      route53:
        command: "create"
        zone: "ovchosting.co.uk"
        hosted_zone_id: "Z3A98VA7X0SL0T"
        private_zone: "true"
        record: "{{ deploy_type }}.ovchosting.co.uk"
        type: "A"
        ttl: 300
        value: "{{ ami_instance.instances[0].private_ip }}"
        overwrite: yes
      tags:
        - dns
  tags:
    - launch_ami
