---

- name: Create RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds

- name: Build Mongo Cluster
  include: _mongo-create-auto.yml
  remote_user: ec2-user
  tags:
    - tagged
    - mongo

- name: Build Mongo Cluster
  include: _mongo-create-single.yml
  remote_user: ec2-user
  tags:
    - tagged
    - mongo_single

- name: Build PE (Combined)
  include: _pe_combined.yml
  remote_user: ec2-user
  tags:
    - tagged
    - promo

- name: Build PE (NoSSL)
  include: _pe_nonssl.yml
  remote_user: ec2-user
  tags:
    - tagged
    - promo_nossl

- name: Build PE (SSL)
  include: _pe_ssl.yml
  remote_user: ec2-user
  tags:
    - tagged
    - pe_ssl

- name: Find AMI ID
  hosts: localhost
  connection: local
  roles:
    - findovcami
  tags:
    - asg
    - find_ovc_ami

- name: Add AMI ID to facts
  hosts: localhost
  connection: local
  tasks:
    - name: Use set_fact to AMI
      set_fact:
        image_id: "{{ ami_find.results[0].ami_id }}"
      when: image_id is undefined
  tags:
    - asg
    - find_ovc_ami

- hosts: localhost
  connection: local
  tasks:
    - name: Present new AMI ID
      pause:
        prompt: PreProd will now be launched with {{ image_id }}
        seconds: 30

- name: Create ELB and ASG
  include: _asg_main.yml
  vars:
    deploy_pos: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "lc-{{ deploy_type }}-{{ ansible_date_time.epoch }}_config"
  tags:
    - asg
