---
- name: Create a new ELB for DASH
  hosts: localhost
  connection: local
  gather_facts: False


  tasks:
  - name: create ELB DASH
    local_action:
      module: ec2_elb_lb
      name: "{{ deploy_dash }}"
      state: present
      region: "{{ region }}"
      scheme: internal
      connection_draining_timeout: 120
      idle_timeout: 300
      subnets: "{{ elbsubnets }}"
      security_group_ids: "{{ security_group_ids }}"
      listeners:
      - protocol: http
        load_balancer_port: 80
        instance_protocol: http
        instance_port: 80
      - protocol: https
        load_balancer_port: 443
        instance_protocol: https
        instance_port: 443
        ssl_certificate_id: "arn:aws:iam::063725663692:server-certificate/elbs-ovchosting-promo"
      stickiness:
        type: loadbalancer
        enabled: yes
        expiration: 300
      health_check:
        ping_protocol: tcp # options are http, https, ssl, tcp
        ping_port: 443
        ping_path: "/ovcdashboard/login" # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 30 # seconds
        unhealthy_threshold: 2
        healthy_threshold: 10
#      access_logs:
#        interval: 5 # minutes (defaults to 60)
#        s3_location: "sglogs" # This value is required if access_logs is set
#        s3_prefix: "{{ deploy_type }}ELBlogs"
    register: elb_new

  - name: debug elb create
    debug: "var=elb_new"

  - name: Get ELB details after creation
    local_action:
      module: ec2_elb_facts
      names:
        - "{{ deploy_dash }}"
      region: "{{ region }}"
    register: elb_facts

  - name: Add new Route53 entry
    route53:
      command: "create"
      zone: "{{ dns_domain }}"
      hosted_zone_id: "Z3A98VA7X0SL0T"
      private_zone: "true"
      record: "{{ deploy_type }}-dash.{{ dns_domain }}"
      type: "CNAME"
      ttl: 300
      value: "{{ elb_facts.elbs.0.dns_name }}"
      overwrite: yes
