---
- name: ASG and ELB Deploy
  hosts: localhost
  remote_user: ec2-user
  gather_facts: False

  tasks:
  - include_vars: vars/ami-baker-defaults.yml
  - include_vars: vars/settings.yml

# install ELB POS
- include: create-elb-pos.yml
  vars:
    ovc_version: "5.4.0"
    deploy_type: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    elbsubnets: "subnet-ac2d02f5,subnet-cae8ffbd,subnet-d4a14fb0"
    ovc_security_groups: "sg-887dc9ef"
    IAMROLE: "CodeDeploy-EC2"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "{{ deploy_type }}_config"
    instance_type_asg: m4.xlarge

# install ELB DASH
- include: create-elb-dash.yml
  vars:
    ovc_version: "5.4.0"
    deploy_type: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    elbsubnets: "subnet-ac2d02f5,subnet-cae8ffbd,subnet-d4a14fb0"
    ovc_security_groups: "sg-887dc9ef"
    IAMROLE: "CodeDeploy-EC2"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "{{ deploy_type }}_config"
    instance_type_asg: m4.xlarge

# install ASG
- include: create-auto.yml
  vars:
   ovc_version: "5.4.0"
   deploy_type: "{{ deploy_type }}-POS"
   deploy_dash: "{{ deploy_type }}-Dash"
   elbsubnets: "subnet-ac2d02f5,subnet-cae8ffbd,subnet-d4a14fb0"
   ovc_security_groups: "sg-887dc9ef"
   IAMROLE: "CodeDeploy-EC2"
   asg_name: "{{ deploy_type }}_autoscale"
   new_lc_name: "{{ deploy_type }}_config"
   instance_type_asg: m4.xlarge
