---
- name: ASG and ELB Deploy
  hosts: localhost
  remote_user: ec2-user
  gather_facts: False

  tasks:
  - include_vars: vars/settings.yml

- name: Create ELB for POS
  include: create-elb-pos.yml

- name: Create ELB for Dashboard
  include: create-elb-dash.yml

- name: Create Launch Config and Auto Scaling Group
  include: create-auto.yml
