---
- name: ASG and ELB Deploy
  hosts: localhost
  remote_user: ec2-user
  gather_facts: False

  tasks:
  - include_vars: vars/settings.yml

# install ELB POS
- include: create-elb-pos.yml
  vars:
    deploy_pos: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "{{ deploy_type }}_config"

# install ELB DASH
- include: create-elb-dash.yml
  vars:
    deploy_pos: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "{{ deploy_type }}_config"

# install ASG
- include: create-auto.yml
  vars:
   deploy_pos: "{{ deploy_type }}-POS"
   deploy_dash: "{{ deploy_type }}-Dash"
   asg_name: "{{ deploy_type }}_autoscale"
   new_lc_name: "{{ deploy_type }}_config"
