- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - include_vars: roles/ec2-create/defaults/main.yml

  - name: launch temporary instance
    local_action:
      module: ec2
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ key }}"
      group_id: "{{ ovc_security_groups }}"
      instance_type: "{{ instance_type }}"
      vpc_subnet_id: "{{ vpc_subnet_public }}"
      image: "ami-6c585f06"
      wait: yes
      wait_timeout: 500
      exact_count: 1
      count_tag:
        Name: ami_testing
      instance_tags:
        Name: ami_testing
    register: ami_instance

  - name: debug
    debug: var=ami_instance
