---
- hosts: localhost
  tasks:
    - name: Creating Beanstalk application
      elasticbeanstalk_app:
         region: "{{ region }}"
         app_name: "{{ deploy_type }}-Promo"
         description: "{{ deploy_type }} Promo Engine"
         state: present
      register: application

    - debug: var=application

    - name: Versioning the application
      elasticbeanstalk_version:
         region: "{{ region }}"
         app_name: "{{ deploy_type }}-Promo"
         version_label: "{{ pe_version }}"
         s3_bucket: "{{ s3_bucket }}"
         s3_key: Dockerrun.aws.json.zip
         state: present
      register: version

    - debug: var=version

    - name: Create new Beanstalk environment
      elasticbeanstalk_env:
         region: "{{ region }}"
         app_name: "{{ deploy_type }}-Promo"
         env_name: "{{ deploy_type }}Promo-env"
         tier_name: "{{ tier }}"
         version_label: "{{ pe_version }}"
         solution_stack_name: "{{ solution_stack_name }}"
         option_settings:
           - Namespace: aws:elb:loadbalancer
             OptionName: CrossZone
             Value: true
           - Namespace: aws:elasticbeanstalk:application
             OptionName: Application Healthcheck URL
             Value: TCP:22
           - Namespace: aws:elb:listener
             OptionName: ListenerEnabled
             Value: false
           - Namespace: aws:elb:listener:3000
             OptionName: ListenerProtocol
             Value: HTTPS
           - Namespace: aws:elb:listener:3000
             OptionName: InstanceProtocol
             Value: HTTP
           - Namespace: aws:elb:listener:3000
             OptionName: InstancePort
             Value: 3000
           - Namespace: aws:elb:listener:3000
             OptionName: SSLCertificateId
             Value: "arn:aws:iam::063725663692:server-certificate/elbs-ovchosting-promo"
           - Namespace: aws:elb:listener:8888
             OptionName: InstanceProtocol
             Value: HTTP
           - Namespace: aws:elb:listener:8888
             OptionName: ListenerProtocol
             Value: HTTPS
           - Namespace: aws:elb:listener:8888
             OptionName: InstancePort
             Value: 8888
           - Namespace: aws:elb:listener:8888
             OptionName: SSLCertificateId
             Value: "arn:aws:iam::063725663692:server-certificate/elbs-ovchosting-promo"
           - Namespace: aws:autoscaling:asg
             OptionName: MinSize
             Value: "{{ min_size }}"
           - Namespace: aws:autoscaling:asg
             OptionName: MaxSize
             Value: "{{ max_size }}"
           - Namespace: aws:elb:loadbalancer
             OptionName: SecurityGroups
             Value: "{{ security_group_ids }}"
           - Namespace: aws:elb:loadbalancer
             OptionName: ManagedSecurityGroup
             Value: "{{ elb_security_group_id }}"
           - Namespace: aws:elasticbeanstalk:environment
             OptionName: ServiceRole
             Value: aws-elasticbeanstalk-service-role
           - Namespace: aws:elasticbeanstalk:environment
             OptionName: EnvironmentType
             Value: LoadBalanced
           - Namespace: aws:ec2:vpc
             OptionName: Subnets
             Value: "{{ elbsubnets }}"
           - Namespace: aws:ec2:vpc
             OptionName: VPCId
             Value: "{{ vpc_id }}"
           - Namespace: aws:ec2:vpc
             OptionName: ELBSubnets
             Value: "{{ elbsubnets }}"
           - Namespace: aws:ec2:vpc
             OptionName: ELBScheme
             Value: internal
           - Namespace: aws:ec2:vpc
             OptionName: AssociatePublicIpAddress
             Value: true
           - Namespace: aws:autoscaling:launchconfiguration
             OptionName: IamInstanceProfile
             Value: aws-elasticbeanstalk-ec2-role
           - Namespace: aws:autoscaling:launchconfiguration
             OptionName: InstanceType
             Value: "{{ instance_type_pe }}"
           - Namespace: aws:autoscaling:launchconfiguration
             OptionName: SecurityGroups
             Value: "{{ security_group_ids }}"
           - Namespace: aws:autoscaling:launchconfiguration
             OptionName: EC2KeyName
             Value: "{{ key }}"

    - name: Record ELB EndpointURL
      command: "aws elasticbeanstalk describe-environments --query='Environments[?EnvironmentName==`{{ deploy_type }}Promo-env` && Status==`Ready`].EndpointURL'"
      register: elb_dns

    - name: debug elb dns
      debug: "var=elb_dns"

    - name: Add Alias to Route53
      route53:
        command: "create"
        zone: "ovcdemo.com"
        record: "{{ deploy_type }}-promo.ovchosting.co.uk"
        type: "A"
        private_zone: "true"
        value: "{{ elb_dns.stdout }}"
        alias: "True"
        alias_hosted_zone_id: "{{ alias_hosted_zone }}"
        overwrite: yes
