---

- name: Create Utility RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds_util
  vars:
    environment_name: util-rds
    rds_security_group: "{{ ami_baker_rds_security_group }}"
    rds_subnet_group: "{{ ami_baker_rds_subnet_group }}"
    multirdszone: no

- name: Build temporary instance
  hosts: localhost
  remote_user: ec2-user
  connection: local
  gather_facts: False
  roles:
    - { role: find_ami, when: customer == 'vanilla' or full_build }
    - { role: find_ovc_ami, when: customer != 'vanilla' }
    - ami_baker_pre
  vars:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    region: "{{ region }}"
    key: "{{ key }}"
    ovc_security_groups: "{{ ami_baker_ovc_security_groups }}"
    vpc_subnet_public: "{{ ami_baker_vpc_subnet_public }}"
    instance_type: m4.large
    jetty_user_login: jetty
    jetty_dir: /opt/jetty
    ovc_server_user_dir: /opt/ovc
    webserver_user: www-data
    s3install: true
    ovcDB_host: "utility-mysql.{{ dns_domain }}"
    ovcNOSQLDB_host: "mongodb-utility01.{{ dns_domain }}"

- hosts: just_baked
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - { role: common, when: customer == 'vanilla' or full_build or full_build }
    - { role: jetty, when: customer == 'vanilla' or full_build }
    - { role: oneview, when: customer == 'vanilla' or full_build }

    - { role: install_customizations_dt, when: customer == 'dt' }
    - { role: install_customizations_tp, when: customer == 'tp' }
    - { role: install_customizations_gstar, when: customer == 'gs' }
#    - { role: install_customizations_demo, when: customer == 'ovc' }

    - { role: ricbra.logentries, when: customer == 'vanilla' or full_build }
    - { role: nginx_proxy, when: customer == 'vanilla' or full_build }
    - { role: newrelic_infrastructure, when: customer == 'vanilla' or full_build }

    - { role: install_devops_dt, when: customer == 'dt' }
    - { role: install_devops_tp, when: customer == 'tp' }
#    - { role: install_devops_gstar, when: customer == 'gs' }
    - { role: install_devops_demo, when: customer == 'ovc' }
  vars:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    region: "{{ region }}"
    key: "{{ key }}"
    ovc_security_groups: "{{ ami_baker_ovc_security_groups }}"
    vpc_subnet_public: "{{ ami_baker_vpc_subnet_public }}"
    instance_type: m4.large
    jetty_user_login: jetty
    jetty_dir: /opt/jetty
    ovc_server_user_dir: /opt/ovc
    webserver_user: www-data
    s3install: true
    ovcDB_host: "utility-mysql.{{ dns_domain }}"
    ovcNOSQLDB_host: "mongodb-utility01.{{ dns_domain }}"


- hosts: localhost
  connection: local
  roles:
    - ami_baker_post
  vars:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    region: "{{ region }}"
    key: "{{ key }}"
    ovc_security_groups: "{{ ami_baker_ovc_security_groups }}"
    vpc_subnet_public: "{{ ami_baker_vpc_subnet_public }}"
    instance_type: m4.large
    jetty_user_login: jetty
    jetty_dir: /opt/jetty
    ovc_server_user_dir: /opt/ovc
    webserver_user: www-data
    s3install: true
    ovcDB_host: "utility-mysql.{{ dns_domain }}"
    ovcNOSQLDB_host: "mongodb-utility01.{{ dns_domain }}"
