---
- name: Create a new ELB for OVC POS
  hosts: localhost
  connection: local
  gather_facts: False


  tasks:
  - name: create ELB
    local_action:
      module: ec2_elb_lb
      name: "{{ deploy_type }}"
      state: present
      region: "{{ region }}"
      scheme: internal
      connection_draining_timeout: 120
      idle_timeout: 300
      subnets: "{{ elbsubnets }}"
      security_group_ids: "sg-887dc9ef,sg-9fbd1ef8"
      listeners:
      - protocol: tcp
        load_balancer_port: 443
        instance_port: 443
      - protocol: tcp
        load_balancer_port: 8080
        instance_port: 8080
      health_check:
        ping_protocol: http # options are http, https, ssl, tcp
        ping_port: 80
        ping_path: "/ovcdashboard/login" # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 30 # seconds
        unhealthy_threshold: 2
        healthy_threshold: 10
#      access_logs:
#        interval: 5 # minutes (defaults to 60)
#        s3_location: "sglogs" # This value is required if access_logs is set
#        s3_prefix: "{{ deploy_type }}ELBlogs"
    register: elb_new

  - name: debug elb create
    debug: "var=elb_new"

  - name: Get ELB details after creation
    local_action:
      module: ec2_elb_facts
      names:
        - "{{ deploy_type }}"
      region: "{{ region }}"
    register: elb_facts

  - name: Add new Route53 entry
    route53:
      command: "create"
      zone: "ovchosting.co.uk"
      hosted_zone_id: "Z3A98VA7X0SL0T"
      private_zone: "true"
      record: "preprod.ovchosting.co.uk"
      type: "CNAME"
      ttl: 300
      value: "{{ elb_facts.elbs.0.dns_name }}"
      overwrite: yes


