---
# Mongo playbook will install a three server cluster

#create first server
- name: Create first server
  hosts: localhost
  vars:
    count: 01
  connection: local
  gather_facts: False
  roles:
   - find_ami
   - create_server

  tasks:
   - name: Clear hosts template
     file: path=hosts state=absent

   - name: add host to group
     add_host: name={{ item.private_ip }} groups=just_created
     with_items: ami_instance.instances

   - name: create hosts file
     shell: echo "{{ item.private_ip }} mongodb0{{ count }}.preprod-int.ovchosting.co.uk mongodb0{{ count }}" >> hosts
     with_items: ami_instance.instances

  - name: Add new Route53 entry
    route53:
     command: "create"
     zone: "preprod-int.ovchosting.co.uk"
     hosted_zone_id: "Z3M7I9GRTY3KIG"
     private_zone: "true"
     record: "mongodb0{{ count }}.preprod-int.ovchosting.co.uk"
     type: "A"
     ttl: 7200
     value: "{{ groups.just_created[0] }}"
     overwrite: yes
    with_items: ami_instance.instances

   - name: wait for ssh to come up
     wait_for: host={{ item.private_ip }} delay=60 port=22 state=started timeout=320
     with_items: ami_instance.instances

#create second server
- name: Create second server
  hosts: localhost
  vars:
    count: 02
  connection: local
  gather_facts: False
  roles:
   - create_server

  tasks:
   - name: add host to group
     add_host: name={{ item.private_ip }} groups=just_created
     with_items: ami_instance.instances

   - name: create hosts file
     shell: echo "{{ item.private_ip }} mongodb0{{ count }}.preprod-int.ovchosting.co.uk mongodb0{{ count }}" >> hosts
     with_items: ami_instance.instances

   - name: Add new Route53 entry
     route53:
      command: "create"
      zone: "preprod-int.ovchosting.co.uk"
      hosted_zone_id: "Z3M7I9GRTY3KIG"
      private_zone: "true"
      record: "mongodb0{{ count }}.preprod-int.ovchosting.co.uk"
      type: "A"
      ttl: 7200
      value: "{{ groups.just_created[1] }}"
      overwrite: yes
     with_items: ami_instance.instances

#create third server
- name: Create third server
  hosts: localhost
  vars:
    count: 03
  connection: local
  gather_facts: False
  roles:
   - create_server

  tasks:
   - name: add host to group
     add_host: name={{ item.private_ip }} groups=just_created
     with_items: ami_instance.instances

   - name: create hosts file
     shell: echo "{{ item.private_ip }} mongodb0{{ count }}.preprod-int.ovchosting.co.uk mongodb0{{ count }}" >> hosts
     with_items: ami_instance.instances

  - name: Add new Route53 entry
     route53:
      command: "create"
      zone: "preprod-int.ovchosting.co.uk"
      hosted_zone_id: "Z3M7I9GRTY3KIG"
      private_zone: "true"
      record: "mongodb0{{ count }}.preprod-int.ovchosting.co.uk"
      type: "A"
      ttl: 7200
      value: "{{ groups.just_created[2] }}"
      overwrite: yes
     with_items: ami_instance.instances

- name: Install mongo
  hosts: just_created
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - mongoinstall

  tasks:
    - name: Start mongo on Primary server
      shell: mongod --config /etc/mongod.conf
      when: inventory_hostname == groups.just_created[0]

    - name: Initiate mongo on Primary Server
      shell: "mongo --host {{ groups.just_created[0] }} --eval 'printjson(rs.initiate())' "
      when: inventory_hostname == groups.just_created[0]

    - name: Verify configuration on Primary Server
      shell: "mongo --host {{ groups.just_created[0] }} --eval 'printjson(rs.conf())' "
      when: inventory_hostname == groups.just_created[0]

    - name: Start mongo on Other Servers
      shell: mongod --config /etc/mongod.conf
      when: inventory_hostname != groups.just_created[0]

    - name: Add mongodb02 to the cluster
      shell: mongo --host {{ groups.just_created[0] }} --eval 'printjson(rs.add("{{ groups.just_created[1] }}:27017"))'
      when: inventory_hostname == groups.just_created[1]

    - name: Add mongodb03 to the cluster
      shell: mongo --host {{ groups.just_created[0] }} --eval 'printjson(rs.add("{{ groups.just_created[2] }}:27017"))'
      when: inventory_hostname == groups.just_created[2]

    - name: Copy setAuth.js to Primary
      copy:
        src: setAuth.js
        dest: /opt/setAuth.js
        mode: 0644
      when: inventory_hostname == groups.just_created[0]
      become: yes
      become_user: root

    - name: Execute setAuth.js
      shell: mongo --host {{ groups.just_created[0] }} < /opt/setAuth.js
      when: inventory_hostname == groups.just_created[0]
