---
# Mongo playbook will install a three server cluster

#create first server
- name: Create first server
  hosts: localhost
  vars:
    count: 01
  connection: local
  gather_facts: False
  roles:
    - find_ami
    - create_server

  tasks:
    - name: add host to group
     add_host: name="{{ item.private_ip }}" groups=just_created
     with_items: ami_instance.instances

    - name: Add new Route53 entry
     route53:
       command: "create"
       zone: "ovchosting.co.uk"
       hosted_zone_id: "Z3A98VA7X0SL0T"
       private_zone: "true"
       record: "mongodb-{{ deploy_type }}0{{ count }}.ovchosting.co.uk"
       type: "A"
       ttl: 60
       value: "{{ groups.just_created[0] }}"
       overwrite: yes
     with_items: ami_instance.instances


#create second server
- name: Create second server
  hosts: localhost
  vars:
    count: 02
  connection: local
  gather_facts: False
  roles:
    - create_server

  tasks:
    - name: add host to group
     add_host: name="{{ item.private_ip }}" groups=just_created
     with_items: ami_instance.instances

    - name: Add new Route53 entry
     route53:
       command: "create"
       zone: "ovchosting.co.uk"
       hosted_zone_id: "Z3A98VA7X0SL0T"
       private_zone: "true"
       record: "mongodb-{{ deploy_type }}0{{ count }}.ovchosting.co.uk"
       type: "A"
       ttl: 60
       value: "{{ groups.just_created[1] }}"
       overwrite: yes
     with_items: ami_instance.instances
  tags:
    - mongo_replica

#create third server
- name: Create third server
  hosts: localhost
  vars:
    count: 03
  connection: local
  gather_facts: False
  roles:
    - create_server

  tasks:
    - name: add host to group
     add_host: name="{{ item.private_ip }}" groups=just_created
     with_items: ami_instance.instances

    - name: Add new Route53 entry
     route53:
       command: "create"
       zone: "ovchosting.co.uk"
       hosted_zone_id: "Z3A98VA7X0SL0T"
       private_zone: "true"
       record: "mongodb-{{ deploy_type }}0{{ count }}.ovchosting.co.uk"
       type: "A"
       ttl: 60
       value: "{{ groups.just_created[2] }}"
       overwrite: yes
     with_items: ami_instance.instances

    - name: wait for ssh to come up
     wait_for: host="{{ item.private_ip }}" delay=300 port=22 state=started timeout=1200
     with_items: ami_instance.instances
  tags:
    - mongo_replica

- name: Install mongo
  hosts: just_created
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - Datadog.datadog
    - mongo_automation
  vars:
    datadog_api_key: "e4cbd7941e565adf937353883df89b2d"
