---
- hosts: uat2
  become: yes
  become_user: root
  roles:
    - { role: monit, monit_services: [ jetty: {name: "jetty", type: "process", target: "/var/run/jetty.pid", start: "/sbin/service jetty start", stop: "/sbin/service jetty stop", rules: ["if failed port 8080 protocol http then restart", "if 5 restarts within 5 cycles then timeout"] }, monit_webinterface_enabled: true, monit_webinterface_bind: 127.0.0.1, monit_webinterface_acl_rules: [allow localhost] ]}
