---

- hosts: all
  connection: local
  tasks:
    - name: Dump MySQL
      delegate_to: localhost
      mysql_db:
        state: dump
        name: xdb
        target: "xdb_{{ env_name }}_{{ ansible_date_time.date }}.sql"
        login_host: "{{ inventory_hostname }}"
        login_password: "{{ login_password }}"
        login_user: "{{ login_user }}"
    - name: Upload to S3
      delegate_to: localhost
      s3:
        mode: put
        bucket: ovc-tp-db-backups
        object: "{{ env_name }}/xdb_{{ env_name }}_{{ ansible_date_time.date }}.sql"
        src: "xdb_{{ env_name }}_{{ ansible_date_time.date }}.sql"
