---

#- name: This play will install the ami-builder and mongo cluster


- name: Install Utility RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds_util
  vars:
  environment_name: util-rds
  rds_security_group: sg-5bbc1f3c
  rds_subnet_group: "uat1 rds subnet group"
  multirdszone: no

- name: Install RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds
  vars:
    environment_name: preprod-rds
    rds_security_group: sg-5bbc1f3c
    rds_subnet_group: pre-prod-rds
    multirdszone: no

- name: Install Mongo Cluster
  include: mongo-cluster.yml
  remote_user: ec2-user
  tags:
    - mongo
  vars:
   region: eu-west-1
   key: ovc-travis
   ovc_security_groups: sg-5bbc1f3c
   vpc_subnet_public: subnet-0a75a06e
   instance_type: m4.large
   env: preprod.ovchosting.co.uk
   cluster_name: preprod_cluster
   deploy_type: "preprod"

- name: install ami-builder
  include: ami-baker.yml
  tags:
    - bake_ami
  vars:
    ovc_version: "5.4.0"
    region: eu-west-1
    key: ovc-travis
    ovc_security_groups: sg-71bc1f16
    vpc_subnet_public: subnet-cae8ffbd
    instance_type: m4.large
    asg_name: "preprod_autoscale"
    deploy_pos: "PreProd-POS"
    deploy_dash: "PreProd-Dash"
    deploy_type: "preprod"
    jetty_user_login: jetty
    jetty_dir: /opt/jetty
    ovc_server_user_dir: /opt/ovc
    webserver_user: www-data
    s3install: true
    asg_desired_capacity: 2

- name: Install ELB and ASG
  include: asg_main.yml
  tags:
    - asg
  vars:
    IAMROLE: "CodeDeploy-EC2"
    region: eu-west-1
    key: ovc-travis
    ovc_version: "5.4.0"
    ovc_security_groups: ['sg-71bc1f16']
    deploy_type: "preprod"
    deploy_pos: "{{ deploy_type }}-POS"
    deploy_dash: "{{ deploy_type }}-Dash"
    asg_name: "{{ deploy_type }}_autoscale"
    new_lc_name: "{{ deploy_type }}_config"
    min_size: 2
    max_size: 5
    instance_type_asg: m4.xlarge
    security_group_ids: "sg-887dc9ef,sg-9fbd1ef8,sg-71bc1f16"
    elbsubnets: "subnet-ac2d02f5,subnet-cae8ffbd,subnet-d4a14fb0"
