---

#- name: This play will install the ami-builder and mongo cluster

- name: Install Mongo Cluster
  include: mongo-cluster.yml
  hosts: localhost
  remote_user: ec2-user
  gather_facts: False
  vars:
   region: eu-west-1
   key: ovc-travis
   ovc_security_groups: sg-5e4aaf39 # FIXME: Wrong
   vpc_subnet_public: subnet-bc9790e5 # FIXME: Wrong
   instance_type: m4.large
   env: prod.ovchosting.co.uk
   cluster_name: prod_cluster

- name: install ami-builder
  include: ami-baker.yml
  vars:
    ovc_version: "5.4.0"
    region: eu-west-1
    key: ovc-travis
    ovc_security_group: sg-5e4aaf39  #FIXME
    instance_type: m4.large
    instance_type_asg: m4.xlarge
    asg_name: "Prod_autoscale"
    vpc_subnet_public: subnet-bc9790e5 #FIXME
    deploy_pos: "Prod-POS"
    deploy_dash: "Prod-Dash"
    jetty_user_login: jetty
    jetty_dir: /opt/jetty
    ovc_server_user_dir: /opt/ovc
    webserver_user: www-data
    s3install: true
    asg_desired_capacity: 2

- name: Install ELB and ASG
  include: asg_main.yml
