---

- hosts: tag_environment_prod:&tag_role_webapp
  remote_user: ec2-user
  become: yes
  become_user: jetty
  tasks:
    - name: Run devAll
      run_once: yes
      command: /opt/ovc/bin/initDevAll.sh
      async: 1200
      poll: 30
      tags:
        - tagged
        - devAll

    - name: Run eComRefresh
      run_once: yes
      command: /opt/ovc/bin/eComRefresh.sh
      async: 7200
      poll: 60
      tags:
        - tagged
        - ecomrefresh

    - name: Run initStaffDiscount
      run_once: yes
      command: /opt/ovc/bin/initStaffDiscount.sh
      async: 1200
      poll: 30
      tags:
        - tagged
        - staffdiscount
