---

#- name: This play will install the ami-builder and mongo cluster


- name: Create Utility RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds_util
  vars:
    environment_name: rds-utility
    rds_security_group: sg-5bbc1f3c
    rds_subnet_group: "uat1 rds subnet group"
    multirdszone: no

- name: Create RDS
  connection: local
  hosts: localhost
  roles:
    - create_rds
  tags:
    - rds
  vars:
    environment_name: uat1-rds
    rds_security_group: sg-a50010c1
    rds_subnet_group: "uat1 rds subnet group"
    multirdszone: no

- name: Build Mongo Cluster
  pause:
    prompt: Please confirm that mongodb-uat1.ovchosting.co.uk is available, press enter when ready.

- name: Find AMI ID
  hosts: localhost
  connection: local
  roles:
    - findovcami
  tags:
    - asg
    - find_ovc_ami
  vars:
   region: eu-west-1

- name: Add AMI ID to facts
  hosts: localhost
  connection: local
  tasks:
    - name: Use set_fact to AMI
      set_fact:
        image_id: "{{ ami_find.results[0].ami_id }}"
      when: image_id is undefined
  tags:
    - asg
    - find_ovc_ami


- name: Launch instance for UAT1
  tasks:
    - name: Present new AMI ID
      pause:
        prompt: UAT1 will now be launched with {{ image_id }}
    - name: Launch instance
      ec2:
        assign_public_ip: yes
        region: eu-west-1
        key_name: ovc-tp-np
        group_id: sg-2b00104f, sg-61001005
        instance_type: m4.xlarge
        vpc_subnet_id: subnet-0ca54b68
        image: "{{ image_id }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: uat1.ovchosting.co.uk
        instance_tags:
          Name: uat1.ovchosting.co.uk
