---
# This playbook contains plays that install mongo

- name: Patch the server before anything.
  yum: name=* state=latest
  sudo: yes

- name: Move new hosts file to server
  template: src=hosts dest=/tmp/hosts

- name: Update hosts file
  shell: cat /tmp/hosts >> /etc/hosts
  become: yes
  become_user: root

- name: Make /data/db
  file: path=/data/db state=directory mode=0755
  become: yes
  become_user: root

- name: Get IP Address
  shell: "ifconfig | grep 'inet addr' | cut -d':' -f2 | cut -d' ' -f1 | grep -v 127.0.0.1"
  register: priv_ip
  become: yes
  become_user: root

- name: Get hostname
  shell: "grep {{ priv_ip.stdout }} /tmp/hosts | cut -d' ' -f'3'"
  register: host_name
  become: yes
  become_user: root

- name: Set hostname
  shell: hostname {{ host_name.stdout }}
  become: yes
  become_user: root

- name: Set persistant hostname
  lineinfile: "dest=/etc/sysconfig/network regexp=HOSTNAME* state=present line='HOSTNAME={{ host_name.stdout }}'"
  become: yes
  become_user: root

- name: Restart Network
  service: name=network state=restarted
  become: yes
  become_user: root

- name: Make mongo repo
  template: src=mongoRepo dest=/etc/yum.repos.d/mongodb-org-3.2.repo
  become: yes
  become_user: root

- name: Install mongo tools
  yum: name=mongodb-org state=latest
  become: yes
  become_user: root

- name: Set private_ip
  set_fact: private_ip="{{ priv_ip.stdout }}"
  become: yes
  become_user: root

- name: Set mongo config
  template: src=mongod.conf dest=/etc/mongod.conf
  become: yes
  become_user: root
