---
# This playbook contains plays that install mongo

- name: Patch the server before anything.
  yum: name=* state=latest
  sudo: yes

- name: Move new hosts file to server
  template: src=hosts dest=/tmp/hosts

- name: Update hosts file
  shell: cat /tmp/hosts >> /etc/hosts

- name: Make /data/db
  file: path=/data/db state=directory mode=0755

- name: Get IP Address
  shell: "ifconfig | grep 'inet addr' | cut -d':' -f2 | cut -d' ' -f1 | grep -v 127.0.0.1"
  register: priv_ip

- name: Get hostname
  shell: "grep {{ priv_ip.stdout }} /tmp/hosts | cut -d' ' -f'3'"
  register: host_name

- name: Set hostname
  shell: hostname {{ host_name.stdout }}

- name: Set persistant hostname
  lineinfile: "dest=/etc/sysconfig/network regexp=HOSTNAME* state=present line='HOSTNAME={{ host_name.stdout }}'"

- name: Restart Network
  service: name=network state=restarted

- name: Make mongo repo
  template: src=mongoRepo dest=/etc/yum.repos.d/mongodb-org-3.2.repo

- name: Install mongo tools
  yum: name=mongodb-org state=latest

- name: Set private_ip
  set_fact: private_ip="{{ priv_ip.stdout }}"

- name: Set mongo config
  template: src=mongod.conf dest=/etc/mongod.conf

