- name: launch temporary instance
  local_action:
    module: ec2
    assign_public_ip: yes
    region: "{{ region }}"
    key_name: "{{ key }}"
    group_id: "{{ ovc_security_groups }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ vpc_subnet_public }}"
    image: "{{ ami_find.results[0].ami_id }}"
    wait: yes
    instance_profile_name: "{{ ami_baker_instance_profile_name }}"
    exact_count: 1
    count_tag:
      role: ami_builder
    instance_tags:
      role: ami_builder
      Name: ami_builder
  register: ami_instance

- name: Set IP fact (public).
  set_fact:
    ssh_ip: "{{ ami_instance.tagged_instances.0.public_ip }}"
  when: use_public_ip

- name: Set IP fact (private).
  set_fact:
    ssh_ip: "{{ ami_instance.tagged_instances.0.private_ip }}"
  when: not use_public_ip

- name: Show IP
  debug:
    var: ssh_ip

- name: wait for ssh to come up
  wait_for: host={{ ssh_ip }} delay=30 port=22 state=started timeout=640
  with_items: ami_instance.instances

- name: Add host to group just_created
  add_host: name={{ ssh_ip }} groups=just_created

- name: Add host to group just_baked
  add_host: name={{ ssh_ip }} groups=just_baked
