- name: Copy package into place
  get_url:
    url: https://cloud.mongodb.com/download/agent/backup/mongodb-mms-backup-agent-latest.x86_64.rpm
    dest: /tmp/mongodb-mms-backup-agent-latest.x86_64.rpm

- name: Install package
  yum:
    name: /tmp/mongodb-mms-backup-agent-latest.x86_64.rpm
    state: present

- name:
  lineinfile:
    regexp: mmsApiKey\=
    line: mmsApiKey=25198105b01633367f6f135c235ae476
    dest: /etc/mongodb-mms/backup-agent.config

- name: Enable and service
  service:
    name: mongodb-mms-backup-agent
    state: started
    enabled: yes
