---

- name: Download Automation Agent
  get_url:
     url: "{{automation_agent_pkg}}"
     dest: /tmp/automation-agent.rpm

- name: Install automation agent
  yum:
    name: /tmp/automation-agent.rpm
    state: present

- name: Create /data directory
  file:
    path=/data
    mode=0755
    state=directory
    owner=mongod
    group=mongod
  become: yes
  become_user: root

- name: Start Automation Agent, and enable start on boot
  service:
    name=mongodb-mms-automation-agent
    state=restarted
    enabled=yes
  become: yes
  become_user: root
