- name: launch temporary instance
  local_action:
    module: ec2
    assign_public_ip: yes
    region: "{{ region }}"
    key_name: "{{ key }}"
    group_id: "{{ ovc_security_groups }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ vpc_subnet_public }}"
    image: "{{ ami_find.results[0].ami_id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
      role: ami_builder
    instance_tags:
      role: ami_builder
      Name: OneViewSourceImage 
  register: ami_instance

- debug: msg="{{  ami_instance.tagged_instances.0.public_ip }}"
#  with_items: "{{ ami_instance.results }}"

- name: Wait for SSH to come up
  wait_for: host={{ ami_instance.tagged_instances.0.public_ip }} port=22 state=started
  when: ami_instance|changed

- name: add host to group
  add_host: name={{ ami_instance.tagged_instances.0.public_ip }} groups=just_created

