- name: Finding latest Amazon Linux ami
  ec2_ami_find:
    name: "ovc-{{ ovc_version }}*"
    sort: name
    sort_order: descending
    region: "{{ region }}" 
    sort_end: 1
  register: ami_find

- debug: msg="{{ ami_find.results }}"

- vars: 
  new_image_id: "{{ ami_find.results[0].ami_id }}"
