---

- name: Download Automation Agent
  get_url: url={{automation_agent_pkg}} dest=/tmp/automation-agent.rpm

- name: Check for existing Automation Agent config file
  #connection: local
  stat: path=/etc/mongodb-mms/automation-agent.config
  register: config_file

- name: Back up Automation Agent config file if exists
  command: mv /etc/mongodb-mms/automation-agent.config /etc/mongodb-mms/automation-agent.config.bak
  become: yes
  become_user: root
  when: config_file.stat.exists

- name: Install automation agent
  #connection: local
  yum: name=/tmp/automation-agent.rpm state=present

- name: Back up Automation Agent config file if exists
  command: mv /etc/mongodb-mms/automation-agent.config /etc/mongodb-mms/automation-agent.config.bak
  become: yes
  become_user: root
  when: config_file.stat.exists

- name: Copy automation config
  copy:
     src: templates/automation-agent.config.j2
     dest: /etc/mongodb-mms/automation-agent.config
     owner: mongod
     group: mongod
     mode: 0755


- name: Collect status on /data directory
  stat: path=/data
  register: data_dir

- name: If /data exists, set ownership to 'mongod'
  command: chown mongod:mongod /data
  become: yes
  become_user: root
  when: data_dir.stat.isdir is defined and data_dir.stat.isdir

- name: If /data not exists, create directory and set ownership to 'mongod'
  shell: mkdir /data && chown mongod:mongod /data
  become: yes
  become_user: root
  when: data_dir.stat.exists == False

- name: Start Automation Agent, and enable start on boot
  service: name=mongodb-mms-automation-agent state=restarted enabled=yes
  become: yes
  become_user: root
