init_config:

instances:
  - name: OVC Dashboard
    url: http://localhost:9080/ovcdashboard/login
    timeout: 5

    collect_response_time: true
    skip_event: true

    tags:
      - check:http
      - process:apache
      - env:unknown

  - name: Jetty
    url: http://localhost:8080/
    timeout: 5

    collect_response_time: true
    skip_event: true

    tags:
      - check:http
      - process:jetty
      - env:unknown

  - name: NGINX
    url: https://localhost:443/
    timeout: 5

    collect_response_time: true
    skip_event: true

    tags:
      - check:http
      - process:nginx
      - env:unknown

  - name: NGINX Dashboard
    url: https://localhost:443/ovcdashboard/login
    timeout: 5

    collect_response_time: true
    skip_event: true

    tags:
      - check:http
      - process:nginx
      - env:unknown
