environments:
  mbsit99:
    name: mbsit99
    url: mbsit99-dash.ovchosting.co.uk
    mysql_host: mysql-mbsit99.ovcdemo.com
    nosql_host: mongodb-mbsit99.ovchosting.co.uk
    nosql_port: 27017
    sqs_queue:
    staff_discount_bucket:
    ecommerce_host: qamysqlhybris.ovcdemo.com
    ovcNOSQLDB_uri: mongodb://root:root@{{nosql_host}}:{{nosql_port}}/{{name}}_xdb?authSource={{name}}_xdb
  dev:
    name: dev
    url: mbdev.mb-ovc.co.uk
    mysql_host: mysql-dev.mb-ovc.co.uk
    nosql_host: mongodb-dev.mb-ovc.co.uk
    nosql_port: 27000
    sqs_queue:
    staff_discount_bucket:
    ecommerce_host: NONE
    ovcNOSQLDB_uri: mongodb://root:root@{{nosql_host}}:{{nosql_port}}/{{name}}_xdb?authSource={{name}}_xdb
