---
ssl_secret_files:
  /etc/ssl/certs/6eb20afcb39167a3.crt: 
    owner: root
    group: root
    mode: "u=r,go="
    content: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgIIEleOl7BziyIwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
      BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
      GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
      LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
      cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTYwNjIyMTU0NTQwWhcN
      MTgwNDAxMTU0NDM4WjBAMSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
      ZWQxGzAZBgNVBAMMEioub3ZjaG9zdGluZy5jby51azCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBALBi471k4hcaH7LjWIbQF3lAX0hUP9giuEq1FFgvPnTs
      phJEyVah5DrqRSEfua7nuYrgaIqC+zH3q3fYGj7fD/MY6stGlCD/Hqr/H0j5rxUS
      YssFvi2rzrJ+37I7f1AACtTf+QGi75w7LDOrEhSjPzcW71Rc5fmvh9izXSAFsKAf
      YzK15yAeKM4rOSmFNNC08cDaBVu9ilB/u8DxLE16JK1BO3hXtt8MsjxkZRa67JZJ
      Kf8XZ7+1946fX9ULi66Agras3bmyfL+lu0w8smyQM47eeydtI7J+I0E0IPkqLSmm
      Em8x/B4n6RdmKE/SbMdSKhv2FFPgceiBVG7STCd8LecCAwEAAaOCAcIwggG+MAwG
      A1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA4GA1Ud
      DwEB/wQEAwIFoDA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8vY3JsLmdvZGFkZHku
      Y29tL2dkaWcyczEtMjU3LmNybDBdBgNVHSAEVjBUMEgGC2CGSAGG/W0BBxcBMDkw
      NwYIKwYBBQUHAgEWK2h0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVw
      b3NpdG9yeS8wCAYGZ4EMAQIBMHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYY
      aHR0cDovL29jc3AuZ29kYWRkeS5jb20vMEAGCCsGAQUFBzAChjRodHRwOi8vY2Vy
      dGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvZ2RpZzIuY3J0MB8GA1Ud
      IwQYMBaAFEDCvSeOzDSDMKIz1/tss/C0LIDOMC8GA1UdEQQoMCaCEioub3ZjaG9z
      dGluZy5jby51a4IQb3ZjaG9zdGluZy5jby51azAdBgNVHQ4EFgQUzeMV4huY1oD+
      R3wZ40hGJK77JpcwDQYJKoZIhvcNAQELBQADggEBABNp/VHOmvcjRsvEdqjSsuVd
      4C5B2X3uXi8yUSV93s1KExuemphz4iUYgMSYQ8u6+nQ4W/1wycFwMvcrEHhhN+LK
      aATmjlOyplgslDLbjaAwiX1kQtC+Wi0DPj7HFhsFy0rAOCm3vWNwzjgaVaCs18er
      QKcMrvmSA7cu22Qwc9UVbgsOcZnu03SZM/VPmwwvsXMtZTojJwes3upzXQfHLOrr
      353Y9qyuWRQSrJe/1QHxR6OiXrKGk61q7F7A3QSdwEo2jSw/95qL6tNwauNaWx7y
      p+JGtZC3UA6zl22iE/btQ0UJeIT4hH3Ow5P5TcCcYnZ7Esc6WJ+5u/4f/VIpbOo=
      -----END CERTIFICATE-----
  /etc/ssl/certs/gd_bundle-g2-g1.crt: 
    owner: root
    group: root
    mode: "u=r,go="
    content: |
      -----BEGIN CERTIFICATE-----
      MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
      EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
      EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
      ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
      MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
      EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
      CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
      EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
      BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
      K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
      cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
      pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
      eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
      AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
      HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
      9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
      b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
      b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
      CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
      MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
      91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
      RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
      DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
      GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
      LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEfTCCA2WgAwIBAgIDG+cVMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNVBAYTAlVT
      MSEwHwYDVQQKExhUaGUgR28gRGFkZHkgR3JvdXAsIEluYy4xMTAvBgNVBAsTKEdv
      IERhZGR5IENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMTAx
      MDcwMDAwWhcNMzEwNTMwMDcwMDAwWjCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgT
      B0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHku
      Y29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1
      dGhvcml0eSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3Fi
      CPH6WTT3G8kYo/eASVjpIoMTpsUgQwE7hPHmhUmfJ+r2hBtOoLTbcJjHMgGxBT4H
      Tu70+k8vWTAi56sZVmvigAf88xZ1gDlRe+X5NbZ0TqmNghPktj+pA4P6or6KFWp/
      3gvDthkUBcrqw6gElDtGfDIN8wBmIsiNaW02jBEYt9OyHGC0OPoCjM7T3UYH3go+
      6118yHz7sCtTpJJiaVElBWEaRIGMLKlDliPfrDqBmg4pxRyp6V0etp6eMAo5zvGI
      gPtLXcwy7IViQyU0AlYnAZG0O3AqP26x6JyIAX2f1PnbU21gnb8s51iruF9G/M7E
      GwM8CetJMVxpRrPgRwIDAQABo4IBFzCCARMwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
      HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMB8GA1Ud
      IwQYMBaAFNLEsNKR1EwRcbNhyz2h/t2oatTjMDQGCCsGAQUFBwEBBCgwJjAkBggr
      BgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMDIGA1UdHwQrMCkwJ6Al
      oCOGIWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Ryb290LmNybDBGBgNVHSAEPzA9
      MDsGBFUdIAAwMzAxBggrBgEFBQcCARYlaHR0cHM6Ly9jZXJ0cy5nb2RhZGR5LmNv
      bS9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAWQtTvZKGEacke+1bMc8d
      H2xwxbhuvk679r6XUOEwf7ooXGKUwuN+M/f7QnaF25UcjCJYdQkMiGVnOQoWCcWg
      OJekxSOTP7QYpgEGRJHjp2kntFolfzq3Ms3dhP8qOCkzpN1nsoX+oYggHFCJyNwq
      9kIDN0zmiN/VryTyscPfzLXs4Jlet0lUIDyUGAzHHFIYSaRt4bNYC8nY7NmuHDKO
      KHAN4v6mF56ED71XcLNa6R+ghlO773z/aQvgSMO3kwvIClTErF0UZzdsyqUvMQg3
      qm5vjLyb4lddJIGvl5echK1srDdMZvNhkREg5L4wn3qkKQmw4TRfZHcYQFHfjDCm
      rw==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEADCCAuigAwIBAgIBADANBgkqhkiG9w0BAQUFADBjMQswCQYDVQQGEwJVUzEh
      MB8GA1UEChMYVGhlIEdvIERhZGR5IEdyb3VwLCBJbmMuMTEwLwYDVQQLEyhHbyBE
      YWRkeSBDbGFzcyAyIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTA0MDYyOTE3
      MDYyMFoXDTM0MDYyOTE3MDYyMFowYzELMAkGA1UEBhMCVVMxITAfBgNVBAoTGFRo
      ZSBHbyBEYWRkeSBHcm91cCwgSW5jLjExMC8GA1UECxMoR28gRGFkZHkgQ2xhc3Mg
      MiBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASAwDQYJKoZIhvcNAQEBBQADggEN
      ADCCAQgCggEBAN6d1+pXGEmhW+vXX0iG6r7d/+TvZxz0ZWizV3GgXne77ZtJ6XCA
      PVYYYwhv2vLM0D9/AlQiVBDYsoHUwHU9S3/Hd8M+eKsaA7Ugay9qK7HFiH7Eux6w
      wdhFJ2+qN1j3hybX2C32qRe3H3I2TqYXP2WYktsqbl2i/ojgC95/5Y0V4evLOtXi
      EqITLdiOr18SPaAIBQi2XKVlOARFmR6jYGB0xUGlcmIbYsUfb18aQr4CUWWoriMY
      avx4A6lNf4DD+qta/KFApMoZFv6yyO9ecw3ud72a9nmYvLEHZ6IVDd2gWMZEewo+
      YihfukEHU1jPEX44dMX4/7VpkI+EdOqXG68CAQOjgcAwgb0wHQYDVR0OBBYEFNLE
      sNKR1EwRcbNhyz2h/t2oatTjMIGNBgNVHSMEgYUwgYKAFNLEsNKR1EwRcbNhyz2h
      /t2oatTjoWekZTBjMQswCQYDVQQGEwJVUzEhMB8GA1UEChMYVGhlIEdvIERhZGR5
      IEdyb3VwLCBJbmMuMTEwLwYDVQQLEyhHbyBEYWRkeSBDbGFzcyAyIENlcnRpZmlj
      YXRpb24gQXV0aG9yaXR5ggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQAD
      ggEBADJL87LKPpH8EsahB4yOd6AzBhRckB4Y9wimPQoZ+YeAEW5p5JYXMP80kWNy
      OO7MHAGjHZQopDH2esRU1/blMVgDoszOYtuURXO1v0XJJLXVggKtI3lpjbi2Tc7P
      TMozI+gciKqdi0FuFskg5YmezTvacPd+mSYgFFQlq25zheabIZ0KbIIOqPjCDPoQ
      HmyW74cNxA9hi63ugyuV+I6ShHI56yDqg+2DzZduCLzrTia2cyvk0/ZM/iZx4mER
      dEr/VxqHD3VILs9RaRegAhJhldXRQLIQTO7ErBBDpqWeCtWVYpoNz4iCxTIM5Cuf
      ReYNnyicsbkqWletNw+vHX/bvZ8=
      -----END CERTIFICATE-----
  /etc/ssl/certs/ovchosting.noencrypt.key: 
    owner: root
    group: root
    mode: "u=r,go="
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpgIBAAKCAQEAsGLjvWTiFxofsuNYhtAXeUBfSFQ/2CK4SrUUWC8+dOymEkTJ
      VqHkOupFIR+5rue5iuBoioL7Mferd9gaPt8P8xjqy0aUIP8eqv8fSPmvFRJiywW+
      LavOsn7fsjt/UAAK1N/5AaLvnDssM6sSFKM/NxbvVFzl+a+H2LNdIAWwoB9jMrXn
      IB4ozis5KYU00LTxwNoFW72KUH+7wPEsTXokrUE7eFe23wyyPGRlFrrslkkp/xdn
      v7X3jp9f1QuLroCCtqzdubJ8v6W7TDyybJAzjt57J20jsn4jQTQg+SotKaYSbzH8
      HifpF2YoT9Jsx1IqG/YUU+Bx6IFUbtJMJ3wt5wIDAQABAoIBAQCjvqn9ILJjD/Vt
      dHCydmvUPFY4Jz49v72mXQRN+U3Z7fcd7o2axx/BMcqLPZB7NtOggUOLkpzvfiTI
      VO3If/umifMuUo8hMrWduMmqTWCkBzV/lA1BCMYSHoY8R8+gzOlBRcs8Ia6fMq+O
      J7nZPtNoqPn1L2ivqqxKF/jTyXR2sCC2znJr/O6LknT/go7wTZVO8rjrFlm3LWQk
      gM4wNiBRrYrEov0bO5Pp0drwPy+XCCkA9D0TqbiICUpAIj6s48Snm1nBKr1rdQ3L
      W2qtbc0hpSLmLrGQ4h54guhOR7kvDeckxWnyrWugYW626Zg1xKtyo4hUynjY4Nxs
      BQl81yWBAoGBAOfKxRoB8LIoNhmOraPu1VfrQ0w3a06JeciUGntkuYEhOZmAqd3y
      n8aS/Kh3BwKJwEpXn6YKMzz+FkCO+s5AltfFkkUEFAr7sfrBIkOq2vOwcus/K9Bc
      z8AtYbzKQU8+Wiq+o4RVVOA0RbhyznUmZwuJXME2SvXDEPUckjkLc07JAoGBAMLO
      yCHeZATeTbg4aoHkAj/NixxAkRgSh/BW7dbXkRJ23YlRVKKzkT7aBcs5bbIkzloc
      sNJ5ID/kg8s/R8hOSzbCg/yZdWHzrK+tTH8UR27dB81k1O9K9g5oAT7Y1erZuo9Q
      xM3KaLyvgGCuKBcjkvQPdLAWvR15c8iYfzOV438vAoGBAJhNXdFG8Ra+4T1NyL5s
      kfYg+ak8yN9j6Ydn+TaW6mT0pdo89mCFqYJa1nUDMLH0PUsb5CS/kwdClPB6gkW/
      nt3MTd3XXiwRUdLH0HHR8+gnSntUmL9iHIfTyeK4qs0c1TY86UhsoUZoUl9t4EaN
      oyuraCz0NbDiKWRFD7c31N4xAoGBAKmBhfC6cqstx9CQ/lPxUuezcOTvZZDdpv1A
      lokHX0sCtLdkVlGQD8TxrnLrkICeuBL+vfkVvjL6Ipd6g3pObfHDBVeJK/NENTFT
      iKlWuuVDXCOjJgjlX/6fDt5hjJliRIupiuVJxyLPTtRRFb80jAzjWfRShNGduVqF
      HsGDHcWvAoGBAJeZYxFrY9qwq5jHLB0NLLeXRM3bMAFq+Nk0s62Qw8Oyu5tgvBI2
      Go5zxTbCRJJt2wZdNdegUAb3KfR203Fl439uhiQ2PdBZuZzKutSGNq9jQvjJapFG
      LLkjkrbAlqnyphld6TxnK//A664WCsaq6FtwkDEZZSLiqxlx3ncXfhEs
      -----END RSA PRIVATE KEY-----
