---
- name: Jetty Server | Load SSL Keys
  include_vars: "ssl-secrets.yml"
  no_log: true

- name: Jetty server | Copy SSL keys
  copy: 
    dest="{{ item.key }}"
    content="{{ item.value.content }}"
    owner="{{ item.value.owner }}"
    group="{{ item.value.group }}"
    mode="{{ item.value.mode }}"
  with_dict: ssl_secret_files
  sudo: yes
#  no_log: true 
