- name: bundle ami
  local_action:
    module: ec2_ami
    instance_id: "{{ just_created_instance_id }}"
    region: "{{ region }}"
    state: present
    description: This was provisioned {{ ansible_date_time.iso8601 }}
    name: ovc-{{ ovc_version }}-{{ ansible_date_time.epoch }}
    wait: yes
    launch_permissions:
      user_ids: ['748109554602', {{ customer_account_id }}]
    tags:
      customer: "{{ ami_customer }}"
      release: "{{ ami_release }}"
  register: amioutput

- name: terminate temporary instance
  local_action:
    module: ec2
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ just_created_instance_id }}"
  tags:
    - terminate_ami

- name: debug
  debug: var=amioutput

- name: Set image_id
  set_fact:
    image_id: "{{ amioutput.image_id }}"
  when: amioutput.image_id is defined
