- set_fact:
    ami_name: "ovc-{{ ovc_version }}-{{ ansible_date_time.epoch }}"
  when: ami_role == 'ami_builder'

- set_fact:
    ami_name: "mongo-mms-{{ ansible_date_time.epoch }}"
  when: ami_role == 'mongo_ami'

- name: Bundle AMI
  local_action:
    module: ec2_ami
    instance_id: "{{ just_created_instance_id }}"
    region: "{{ ami_baker_region }}"
    state: present
    description: This was provisioned {{ ansible_date_time.iso8601 }}
    name: "{{ ami_name }}"
    wait: yes
    wait_timeout: 1500
    launch_permissions:
      user_ids: ['748109554602', "{{ customer_account_id }}"]
    tags:
      customer: "{{ ami_customer }}"
      release: "{{ ami_release }}"
      source: "{{ source_ami }}"
      git_sha: "{{ ovc_git_sha }}"
      git_branch: "{{ ovc_circle_branch }}"
      source_customer: "{{ source_tag_customer }}"
      source_git_branch: "{{ source_tag_git_branch }}"
      source_git_sha: "{{ source_tag_git_sha }}"
      source_release: "{{ source_tag_release }}"
      pos_version: "{{ source_tag_pos_version }}"
      ext_version: "{{ source_tag_ext_version }}"
  register: amioutput

- name: debug
  debug: var=amioutput

- name: wait for ssh to come up
  wait_for:
    host: "{{ ssh_ip }}"
    delay: 30
    port: 22
    state: started
    timeout: 640

- name: Copy AMI - Temporary name for copying/booting
  ec2_ami_copy:
    source_region: "{{ ami_baker_region }}"
    region: "{{ ami_target_region }}"
    source_image_id: "{{ amioutput.image_id }}"
    wait: yes
  register: amicopy
  when: ami_target_region !=  ami_baker_region

- name: debug
  debug: var=amicopy
  when: ami_target_region != ami_baker_region

- name: Tag AMI
  shell:
    cmd: "aws ec2 create-tags  --region {{ ami_target_region }} --resources {{ amicopy.image_id }} --tags Key=customer,Value={{ ami_customer }} Key=release,Value={{ ami_release }} Key=source,Value={{ source_ami }} Key=git_sha,Value={{ ovc_git_sha }} Key=git_branch,Value={{ ovc_circle_branch }}"
  when: ami_target_region !=  ami_baker_region

- name: Share AMI with customer account
  shell:
    cmd: "aws ec2 modify-image-attribute --region {{ ami_target_region }} --image-id {{ amicopy.image_id }} --launch-permission '{\"Add\": [{\"UserId\":\"{{ customer_account_id }}\"}]}'"
  when: ami_target_region !=  ami_baker_region

- name: Set image_id
  set_fact:
    image_id: "{{ amioutput.image_id }}"
  when: amioutput.image_id is defined
