---

- name: Copy Mongo Automation Agent template
  template:
     src: automation-agent.config.j2
     dest: /etc/mongodb-mms/automation-agent.config
     owner: mongod
     group: mongod
     mode: 0755
  become: yes
  become_user: root

- name: Start Automation Agent, and enable start on boot
  service:
    name: mongodb-mms-automation-agent
    state: started
    enabled: yes
  become: yes
  become_user: root
