---

- name: Template out configs
  template:
    src: automation-agent.config.j2
    dest: /etc/mongodb-mms/automation-agent.config

- name: Start Automation Agent, and enable start on boot
  service:
    name: mongodb-mms-automation-agent
    state: started
    enabled: yes
  become: yes
  become_user: root

- name: Overwriting host file from template
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Setting hostname for /etc/sysconfig/network
  template:
    src: network.j2
    dest: /etc/sysconfig/network

- name: Restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
