    - name: Overwriting host file from template
      template:
         src: templates/hosts.j2
         dest: /etc/hosts
    - name: Setting hostname for /etc/sysconfig/network
      template:
         src: templates/network.j2
         dest: /etc/sysconfig/network

    - name: restart network service
      service:
         name: network
         state: restarted
