---
- name: Launch Instance
  ec2:
    image: "{{ ami_find.results[0].ami_id }}"
    instance_type: "{{ InstanceType }}"
    key_name: "{{ SSHKey }}"
    wait: yes
    region: us-east-1
    group_id: "{{ SecurityGroupID }}"
    vpc_subnet_id: "{{ VPCSubnetID }}"
    instance_profile_name: "{{ IAMRole }}"
    assign_public_ip: yes
    user_data: "{{ lookup('file', 'userdata-' + deploy_type ) }}"
    instance_tags:
       Name: SourceImage-{{ deploy_type }}
  register: ec2

- debug: msg="{{ ec2 }}"

- name: wait for ssh to come up
  wait_for: host={{ item.public_ip }} delay=60 port=22 state=started timeout=320
  with_items: ec2.instances
