- name: launch mongodb instances
  local_action:
    module: ec2
    assign_public_ip: yes
    region: "{{ region }}"
    key_name: "{{ key }}"
    group_id: "{{ ovc_security_groups }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ vpc_subnet_public }}"
    image: "{{ ami_find.results[0].ami_id }}"
    wait: yes
    # instance_profile_name: CodeDeploy-EC2
#    exact_count: 3
    count_tag:
      role: mongodb
    instance_tags:
      role: mongodb
      Name: mongodb-{{ env }}
      monitor: true
      environment: "{{ deploy_type }}"
  register: ami_instance

- name: wait for ssh to come up
  wait_for: host={{ item.private_ip }} delay=60 port=22 state=started timeout=320
  with_items: ami_instance.instances
