- name: Stop Jetty
  service:
    name: jetty
    state: stopped
  become: yes
  become_user: root

- name: Remove App-Data
  file: path="{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/App-Data/dt-all" state=absent
  become: yes
  become_user: root

- name: Remove Shared-Data
  file: path="{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/Shared-Data/dt-all" state=absent
  become: yes
  become_user: root

- name: Remove Client-Data
  file: path="{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/Client-Data/dt-all" state=absent
  become: yes
  become_user: root

- name: Remove Server-Data
  file: path="{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/Server-Data/dt-all" state=absent
  become: yes
  become_user: root

- name: Remove ImportFiles
  file: path="{{ ovc_install_dir }}/Base-Location-Import-Files/*" state=absent
  become: yes
  become_user: root

- name: Remove DT jars
  file: path="{{ item }}" state=absent
  with_fileglob:
    - "{{ jetty_dir }}/lib/ext/DT*"
  become: yes
  become_user: root

- name: Create OVC_Customizations
  file:
    path: "{{ ovc_install_dir }}/installFiles/OVC_Customizations"
    state: directory
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Download full zip file
  s3:
    bucket: "{{ s3_bucket_customer }}"
    object: "{{ s3_full_zip_prefix }}/{{ dt_extension_version }}/DTCustomPackage-{{ dt_extension_version }}.zip"
    dest: "/tmp/DTCustomPackage-{{ dt_extension_version }}.zip"
    mode: get
  when: s3_full_zip_prefix is defined and s3_full_zip_prefix != 'false'

- file:
    path: "/tmp/DTCustomPackage-{{ dt_extension_version }}/"
    state: directory

- name: Extract contents of zip file
  unarchive:
    src: "/tmp/DTCustomPackage-{{ dt_extension_version }}.zip"
    dest: "/tmp/DTCustomPackage-{{ dt_extension_version }}/"
    remote_src: True
  when: s3_full_zip_prefix is defined and s3_full_zip_prefix != 'false'

- name: Extract contents of zip file to secondary location
  unarchive:
    src: "/tmp/DTCustomPackage-{{ dt_extension_version }}.zip"
    dest: "{{ ovc_server_user_dir }}/installFiles/"
    remote_src: True
  when: s3_full_zip_prefix is defined and s3_full_zip_prefix != 'false'

- name: Copy dtdata.tar.gz into the right place
  copy:
    src: "/tmp/DTCustomPackage-{{ dt_extension_version }}/OVC_Custom/dtdata.tar.gz"
    dest: "{{ ovc_server_user_dir }}/installFiles/dtdata.tar.gz"
    remote_src: True
  when: s3_full_zip_prefix is defined and s3_full_zip_prefix != 'false'
  tags:
    - separatedtdatazip

- name: Download dtdata.tar.gz from S3
  command: "aws s3 cp s3://{{ s3_bucket_customer }}/{{ s3_full_zip_prefix }}/dtdata.tar.gz {{ ovc_server_user_dir }}/installFiles/dtdata.tar.gz"
  when: s3install is defined and s3install and s3_full_zip_prefix is undefined and not s3_full_zip_prefix
  become: yes
  become_user: root
  tags:
    - separatedtdatazip

- name: Make jetty user own dtdata.tar.gz when downloaded from S3
  file:
    path: "{{ ovc_server_user_dir }}/installFiles/dtdata.tar.gz"
    mode: ug+rw
    owner: "{{ jetty_user_login }}"
    group: "{{ jetty_group_name }}"
  when: s3install is defined and s3install
  become: yes
  become_user: root
  tags:
    - separatedtdatazip

- name: Unarchive dtdata.tar.gz from S3
  unarchive:
    copy: no
    src: "{{ ovc_server_user_dir }}/installFiles/dtdata.tar.gz"
    dest: "{{ ovc_install_dir }}/installFiles/OVC_Customizations"
    owner: "{{ jetty_user_login }}"
    group: "{{ jetty_group_name }}"
  when: s3install is defined and s3install
  become: yes
  become_user: root
  tags:
    - separatedtdatazip

- name: Unarchive dtdata.tar.gz from local
  unarchive:
    src: dtdata.tar.gz
    dest: "{{ ovc_install_dir }}/installFiles/OVC_Customizations"
  when: s3install is not defined or not s3install
  become: yes
  become_user: "{{ jetty_user_login }}"
  tags:
    - separatedtdatazip

- name: Unarchive Custom Data
  unarchive:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Custom/customdata.zip"
    dest: "{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale"
  become: yes
  become_user: root


- name: Unarchive Import Files
  unarchive:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Custom/importfiles.zip"
    dest: "{{ ovc_install_dir }}/installFiles/OVC_Customizations/importFiles/"
  when: s3install is not defined or not s3install


- name: Unarchive Config Files
  unarchive:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Custom/configs.zip"
    dest: "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs/"
  when: s3install is not defined or not s3install



- name: Copy eCommerce Import Files
  synchronize:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Customizations/importFiles/eCommerceImportFiles/"
    dest: "{{ ovc_install_dir }}/Base-Location-Import-Files/ovc-all-OvcStore/eCommerceImportFiles"
  delegate_to: "{{ inventory_hostname }}"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Copy staffDiscountImportFiles Files
  synchronize:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Customizations/importFiles/staffDiscountImportFiles/"
    dest: "{{ ovc_install_dir }}/Base-Location-Import-Files/ovc-all-OvcStore/staffDiscountImportFiles"
  delegate_to: "{{ inventory_hostname }}"


- name: Copy importRootLocations Files
  synchronize:
    src: "{{ ovc_install_dir }}/installFiles/OVC_Customizations/importFiles/importRootLocations/"
    dest: "{{ ovc_install_dir }}/Base-Location-Import-Files/ovc-all-OvcStore/importRootLocations"
  delegate_to: "{{ inventory_hostname }}"



- name: Copy appDataRegistry.config file
  command:  cp "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs/{{ config_folder_name }}/appDataRegistry.config" "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/appDataRegistry.config"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Copy locationWhiteList.ovccfg file
  command: cp "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs//{{ config_folder_name }}/locationWhiteList.ovccfg" "{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/Server-Data/Client-grp-all/config/posMServer/locationWhiteList.ovccfg"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Copy locationGroupMapping.ovccfg file
  command: cp "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs//{{ config_folder_name }}/locationGroupMapping.ovccfg" "{{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/Server-Data/Client-grp-all/config/posMServer/locationGroupMapping.ovccfg"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Copy unifiedConfig.properties file
  command: cp "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs//{{ config_folder_name }}/unifiedConfig.properties" "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties"
  become: yes
  become_user: "{{ jetty_user_login }}"
  tags:
    - copyUnifiedProps

- name: Copy tools.properties file
  command: cp "{{ ovc_install_dir }}/installFiles/OVC_Customizations/configs//{{ config_folder_name }}/tools.properties" "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/tools.properties"
  become: yes
  become_user: "{{ jetty_user_login }}"
  tags:
    - copyToolsProps

- name: Copy Tools jar to lib dir
  copy:
    src: "{{item}}"
    dest: "{{ ovc_install_dir }}/lib/POSMClient-Tools-DT.jar"
  with_fileglob:  POSMClient-Tools-DT-*.jar
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Update Jetty context.xml to include DTTools
  lineinfile:
    dest: "{{ jetty_dir }}/webapps/context.xml"
    insertafter: '<Set name="overrideDescriptor">.*'
    line: '<Set name="extraClasspath">{{ ovc_install_dir }}/lib/POSMClient-Tools-DT.jar</Set>'
  become: yes
  become_user: "{{ jetty_user_login }}"


- name: Edit Jetty start.ini to add plus module
  lineinfile:
    dest: "{{ jetty_dir }}/start.ini"
    line: "--module=plus"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Add configurations to jettys start.ini
  lineinfile:
    dest: "{{ jetty_dir}}/start.ini"
    state: present
    line: "{{ item.line }}"
  with_items:
    - { line: '-Dovc.tempfiles.cleanup=true'}
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Edit Jetty start.ini to add ext module
  lineinfile:
    dest: "{{ jetty_dir }}/start.ini"
    line: "--module=ext"
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Edit tools.properties
  lineinfile:
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/tools.properties"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: '^posMClientSyncUpdater.store.*', line: 'posMClientSyncUpdater.store=All' }
    - { regexp: '^ovcServer.customer-all.*', line: 'ovcServer.customer-all=dt-all' }
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Update unifiedconfig.properties to include hybris OCC configs
  lineinfile:
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^ecommerce.fromServer.occ.type=.*', line: 'ecommerce.fromServer.occ.type=1' }
    - { regexp: '^secure.occhost.context=.*', line: 'secure.occhost.context=/extovcocc' }
    - { regexp: '^export.products.url=.*', line: 'export.products.url=v2/%s/ovc/products/paginated' }
    - { regexp: '^catalogs.url=.*', line: 'catalogs.url=/v2/%s/ovc/merchandisingGroups/All' }
    - { regexp: '^stores.url=.*', line: 'stores.url=/v2/%s/ovc/locations/All' }
    - { regexp: '^export.stock.url=.*', line: 'export.stock.url=v2/%s/ovc/storestock/%s' }
    - { regexp: '^customerDetails.url=.*', line: 'customerDetails.url=/v2/%s/users/%s' }
    - { regexp: '^oAuth.required=.*', line: 'oAuth.required=false' }
    - { regexp: '^products.import.pageSize=.*', line: 'products.import.pageSize=2000' }
    - { regexp: '^others.import.pageSize=.*', line: 'others.import.pageSize=2000' }
    - { regexp: '^secure.occhost.context=.*', line: 'vehicles.url=/v2/%s/ovc/atv/vehicles' }
    - { regexp: '^vehicles.url=.*', line: 'trims.url=/v2/%s/ovc/atv/trims' }
    - { regexp: '^assemblies.url=.*', line: 'assemblies.url=/v2/%s/ovc/atv/assemblies' }
    - { regexp: '^linkedProducts.url=.*', line: 'linkedProducts.url=/v2/%s/ovc/productrelation/paginated' }
    - { regexp: '^vehicleAssemblies.url=.*', line: 'vehicleAssemblies.url=/v2/%s/ovc/atv/vehicleAssemblies' }
    - { regexp: '^chassis.url=.*', line: 'chassis.url=/v2/%s/ovc/atv/chassis' }
    - { regexp: '^certificateFeePriceRules.url=.*', line: 'certificateFeePriceRules.url=/v2/%s/ovc/productrelation/feePriceRules' }
    - { regexp: '^export.product.catalog.name=.*', line: 'export.product.catalog.name=apparelProductCatalog' }
    - { regexp: '^export.product.catalog.version=.*', line: 'export.product.catalog.version=Online' }

  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Copy devAll script
  copy:
    src: initOVCServer.sh
    dest: "{{ ovc_install_dir }}/bin/initOVCServer.sh"
    owner: jetty
    group: jetty
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Cleanup MIME files via devAll
  lineinfile:
    dest: "{{ ovc_install_dir }}/bin/initDevAll.sh"
    line: 'find /tmp/ -type f -name "MIME*" -exec rm {} \;'
  become: yes
  become_user: "{{ jetty_user_login }}"

# - name: Copy Tools jar to posWebapp
#   copy:
#     src: POSMClient-Tools-DT-5.11.0.jar
#     dest: "{{ ovc_install_dir }}/posWebapp/WEB-INF/lib"
#   become: yes
#   become_user: root



#Dumps all databases to hostname.sql
# - name: Backup DB
#   mysql_db:
#     state: dump
#     name: xdb
#     target: /opt/ovc/xdb_back.sql
#     login_user: root
#     login_password: root
#   tags:
#     - dtdbmodify
#   become: yes
#   become_user: root

- name: Import DB
  mysql_db:
    state: import
    name: xdb
    target: /home/ec2-user/MySQL/xdb_dt.sql
    login_user: root
    login_password: root
  tags:
    - dtdbmodify
  become: yes
  become_user: root

- name: Executing clob tbl truncate
  command: mysql -u root -proot xdb -e "truncate table xdb.clob_tbl"
  become: yes
  become_user: root

- name: Run DT SQL
  shell: "mysql -u {{ ovcDB_username }} -p{{ ovcDB_password }} -h {{ ovcDB_host }} {{ ovcDB_db }} < {{ ovc_install_dir }}/Application-Dynamic-Objects/Point-Of-Sale/sql/POSMClient/MySQL/dt-POSMClient-mysql.sql"
  tags:
    - import_custom_db

- name: Remove temp Hash File
  file: path="{{ ovc_install_dir }}/Platform-Dynamic-Objects/temp/" state=absent
  tags:
    - deleteTemp
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: Make OVC directory own by Jetty
  file:
    owner: jetty
    group: jetty
    path: /opt/ovc
  become: yes
  become_user: root

- name: Start Jetty
  service:
    name: jetty
    state: started
  tags:
    - startjetty
  become: yes
  become_user: root
  ignore_errors: yes

- name: Make OVC init script executable
  file:
    path: "{{ ovc_install_dir }}/bin/initOVCServer.sh"
    mode: ug+rwx
    owner: jetty
    group: jetty
  become: yes
  become_user: root

- name: Initialize OneView Server
  shell: "{{ ovc_install_dir }}/bin/initOVCServer.sh"
  become: yes
  become_user: "{{ jetty_user_login }}"
  async:  12000
  poll: 200
  tags:
    - importers
    - dtimporters
  notify: Restart Jetty
