---

- name: ensures New Relic folder exists
  file:
    path="{{newrelic_dir}}"
    state=directory
    mode=0755

- name: ensures New Relic package is present by downloading from s3
  s3:
    bucket: "{{s3_bucket}}"
    object: "newrelic-java-{{newrelic_version}}.zip"
    dest: "{{newrelic_dir}}/newrelic-java-{{newrelic_version}}.zip"
    mode: get

- name: unpack New Relic
  unarchive:
    src="{{newrelic_dir}}/newrelic-java-{{newrelic_version}}.zip"
    dest="{{newrelic_dir}}"
    remote_src=True
    owner=jetty

- name: moves New Relic content to its rightfull place
  shell:
    mv newrelic/* ./; rm -rf newrelic
    chdir="{{newrelic_dir}}"
    creates="{{newrelic_dir}}"/newrelic.jar

- name: configures newrelic.yml
  template:
    src="newrelic.yml.j2"
    dest="{{newrelic_dir}}/newrelic.yml"

- name: run installer
  shell: 
    java -jar newrelic.jar install
    chdir="{{newrelic_dir}}"
  register: installerout
- debug: msg="{{ installerout.stdout }}"

- name: fix the installer brokenness
  lineinfile:
    dest: /etc/init.d/jetty
    regexp: 'newrelic/newrelic.jar'
    line: 'NR_JAR=/opt/jetty-distribution-9.3.7.v20160115/newrelic-java/newrelic.jar; export NR_JAR'
    
#- include: jetty.yml
#  when: newrelic_container == 'jetty'
