---

- name: ensures New Relic folder exists
  file:
    path="{{newrelic_dir}}"
    state=directory
    mode=0755

- name: ensures New Relic package is present by downloading from s3
  s3:
    bucket: "{{s3_bucket}}"
    object: "newrelic-java-{{newrelic_version}}.zip"
    dest: "{{newrelic_dir}}/newrelic-java-{{newrelic_version}}.zip"
    mode: get

- name: unpack New Relic
  unarchive:
    src="{{newrelic_dir}}/newrelic-java-{{newrelic_version}}.zip"
    dest="{{newrelic_dir}}"
    remote_src=True
    owner=jetty

- name: moves New Relic content to its rightfull place
  shell:
    mv newrelic/* ./; rm -rf newrelic
    chdir="{{newrelic_dir}}"
    creates="{{newrelic_dir}}"/newrelic.jar

- name: get the instance ID
  shell: curl -s http://169.254.169.254/latest/meta-data/instance-id
  register: INSTANCE_ID
  tags:
    - ad_hoc
 
- name: get the instances environment tag
  shell: aws ec2 describe-tags --region=eu-west-1 --filters "Name=resource-id,Values={{INSTANCE_ID.stdout}}" "Name=key,Values=environment" --output=text | cut -f5
  register: env_tag
  tags:
    - ad_hoc

- set_fact: 
    newrelic_app_name: "{{ env_tag.stdout }}"
  tags:
    - ad_hoc

- name: configures newrelic.yml
  template:
    src="newrelic.yml.j2"
    dest="{{newrelic_dir}}/newrelic.yml"
  tags:
    - ad_hoc

- name: configures newrelic.yml
  template:
    src="newrelic_ami.yml.j2"
    dest="{{newrelic_dir}}/newrelic.yml"
  tags:
    - baking_ami

- name: run installer
  shell: 
    java -jar newrelic.jar install
    chdir="{{newrelic_dir}}"
  register: installerout
- debug: msg="{{ installerout.stdout }}"

- name: fix the installer brokenness
  lineinfile:
    dest: /etc/init.d/jetty
    regexp: 'newrelic/newrelic.jar'
    line: 'NR_JAR=/opt/jetty-distribution-9.3.7.v20160115/newrelic-java/newrelic.jar; export NR_JAR'
    
#- include: jetty.yml
#  when: newrelic_container == 'jetty'
