---
- hosts: appserver
  become: yes
  become_user: root
  roles:
    - { role: monit, monit_services: [ jetty: {name: "jetty"}, type: "process", target: "/var/run/jetty.pid", start: "/sbin/service jetty start", stop: "/sbin/service jetty stop", rules: ["if failed host 127.0.0.1 port 8080 protocol http then restart", "if 5 restarts within 5 cycles then timeout"] ], monit_webinterface_enabled: false }
