---
# This playbook contains common plays that will be run on all nodes.

- name: Set history to include timestamp
  lineinfile:
    dest: "/home/ec2-user/.bash_profile"
    state: present
    line: 'export HISTTIMEFORMAT="%d/%m/%y %T "'

- name: Install fail2ban
  yum: name=fail2ban state=present
  tags: fail2ban
  become: yes
  become_user: root

- name: Configure fail2ban
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  tags: fail2ban
  notify: restart fail2ban
  become: yes
  become_user: root
