---
# This playbook contains common plays that will be run on all nodes.

- name: Set the timezone to Eastern
  lineinfile:
    dest: "/etc/sysconfig/clock"
    state: present
    regexp: "ZONE=.*"
    line: "ZONE=America/New_York"
  become: yes
  become_user: root

- name: Set the timezone to Eastern
  lineinfile:
    dest: "/etc/sysconfig/clock"
    state: present
    regexp: "ZONE=.*"
    line: "ZONE=America/New_York"
  become: yes
  become_user: root

- name: Stat timezone localtime file
  stat:
    path: "/etc/localtime"
  become: yes
  become_user: root
  register: localtime

- name: Delete timezone localtime if not Eastern
  file:
    dest: "/etc/localtime"
    state: absent
  become: yes
  become_user: root
  when: localtime.stat.islnk != true

- name: Create timezone link of localtime to Eastern
  file:
    dest: "/etc/localtime"
    src: "/usr/share/zoneinfo/America/New_York"
    state: link
  become: yes
  become_user: root

- name: Install fail2ban
  yum: name=fail2ban state=present
  tags: fail2ban
  become: yes
  become_user: root

- name: Configure fail2ban
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  tags: fail2ban
  notify: restart fail2ban
  become: yes
  become_user: root
