---
# This playbook contains common plays that will be run on all nodes.
  - include: amazon.yml
    when: ansible_distribution == 'Amazon'

  - include: centos.yml
    when: ansible_distribution == 'CentOS' 
