- name: Install NGINX
  yum:
    name: nginx
    state: present
  become: yes
  become_user: root

- name: Move Apache to a different port
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: Listen 80
    line: Listen 9080
  become: yes
  become_user: root

- name: Create a chained certificate
  shell: cat /etc/ssl/certs/6eb20afcb39167a3.crt /etc/ssl/certs/gd_bundle-g2-g1.crt > /etc/ssl/certs/6eb20afcb39167a3-chained.crt
  become: yes
  become_user: root
  when: not skip_ssl

- name: Copy in the new NGINX configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  become: yes
  become_user: root

- name: Restart httpd
  service:
   name: httpd
   state: restarted
  become: yes
  become_user: root

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
  become: yes
  become_user: root
  tags:
    - startnginx

- name: Start NGINX (confirm it has been started)
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
  become_user: root
  tags:
    - startnginx
