- name: Install NGINX
  yum:
    name: nginx
    state: present

- name: Move Apache to a different port
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: Listen 80
    line: Listen 9080

- name: Copy in the new NGINX configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644


- name: Restart NGINX
  service:
    name: nginx
    state: restarted
