- name: Add or Update Route53 entry
  route53:
    command: "create"
    zone: "{{ dns_domain }}"
    hosted_zone_id: "{{ dns_zone_id }}"
    private_zone: "true"
    record: "{{ deploy_type }}.{{ dns_domain }}"
    type: "A"
    ttl: 300
    value: "{{ ami_instance.tagged_instances[0].private_ip }}"
    overwrite: "yes"
  when: ami_instance.tagged_instances is defined
  tags:
    - dns
