---

- name: first make sure dest exists.
  file:
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config"
    state: directory
  become: yes
  become_user: root

- name: template out the unifiedConfig.properties files
  template:
    src: unifiedConfig.properties.j2
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/unifiedConfig.properties"
    owner: jetty
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the tools.properties files
  template:
    src: tools.properties.j2
    dest: "{{ ovc_install_dir }}/Platform-Dynamic-Objects/config/tools.properties"
    owner: jetty
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the context.xml files
  template:
    src: context.xml.j2
    dest: "/opt/jetty/webapps/context.xml"
    owner: jetty
    group: jetty
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: Update Jetty context.xml to include DTTools,DTExtensions
  lineinfile:
    dest: "{{ jetty_dir }}/webapps/context.xml"
    insertafter: '<Set name="maxFormContentSize">20000000</Set>'
    line: '<Set name="extraClasspath">{{ ovc_install_dir }}/lib/ext/POSMClient-Tools-DT-{{ dt_extension_version | default(5.4.0) }}.jar,{{ ovc_install_dir }}/lib/ext/DTExtensions-{{ dt_extension_version | default(5.4.0) }}.jar</Set>'
  become: yes
  become_user: "{{ jetty_user_login }}"

- name: template out the database/settings_var.php files
  template:
    src: database.php.j2
    dest: "/var/www/html/ovcdashboard/app/Config/database.php"
    owner: www-data
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: template out the database/settings_var.php files
  template:
    src: setting_var.php.j2
    dest: "/var/www/html/ovcdashboard/app/Config/setting_var.php"
    owner: www-data
    group: www-data
  become: yes
  become_user: root
  with_dict: "{{ environments }}"

- name: Copy the war.xml patch files
  copy:
    src: "{{ item }}"
    dest: /opt/ovc/posWebapp/WEB-INF/
    owner: jetty
    group: jetty
  with_fileglob:
    - cometd/web.xml.patch.*
  become: yes
  become_user: root
